object Frm_PesqPedidoPorNumero: TFrm_PesqPedidoPorNumero
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Pesquisa de Pedido por N'#250'mero'
  ClientHeight = 642
  ClientWidth = 1288
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object DBGrid1: TDBGrid
    Left = 0
    Top = 89
    Width = 1288
    Height = 553
    Align = alClient
    DataSource = DM_Pesq_PedidosPorNumero.DS_Pesquisa
    ReadOnly = True
    TabOrder = 0
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'Tahoma'
    TitleFont.Style = []
    OnDblClick = DBGrid1DblClick
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 1288
    Height = 89
    Align = alTop
    TabOrder = 1
    object Bevel1: TBevel
      Left = 1
      Top = 1
      Width = 1286
      Height = 87
      Align = alClient
      ExplicitLeft = 344
      ExplicitTop = 40
      ExplicitWidth = 50
      ExplicitHeight = 50
    end
    object GroupBox1: TGroupBox
      Left = 16
      Top = 8
      Width = 601
      Height = 73
      Caption = 'Pesquisa'
      TabOrder = 0
      object Label1: TLabel
        Left = 24
        Top = 24
        Width = 63
        Height = 19
        Caption = 'N'#250'mero:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object Edt_Pesquisa: TEdit
        Left = 93
        Top = 21
        Width = 156
        Height = 27
        CharCase = ecUpperCase
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object Btn_Pesquisar: TBitBtn
        Left = 255
        Top = 13
        Width = 137
        Height = 47
        Caption = 'Pesquisar'
        Default = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = Btn_PesquisarClick
      end
    end
  end
end
